// Bancos de palabras de la Sopa de letras (MAYÚSCULAS, sin tildes ni Ñ, de 4 a 11 letras).
export const TEMAS = {
  animales: { nombre: 'Animales', icono: '🐘', palabras: 'PERRO GATO CABALLO ELEFANTE JIRAFA LEON TIGRE DELFIN TORTUGA PINGUINO CONEJO GALLINA MONO LOBO CEBRA AGUILA BALLENA CANGURO SERPIENTE MARIPOSA HORMIGA TIBURON PATO RANA ZORRO BUHO' },
  frutas: { nombre: 'Frutas', icono: '🍓', palabras: 'MANZANA PERA PLATANO NARANJA LIMON FRESA SANDIA MELON CEREZA KIWI MANGO CIRUELA MELOCOTON GRANADA PAPAYA COCO HIGO MORA MANDARINA AGUACATE ARANDANO FRAMBUESA DATIL LIMA' },
  paises: { nombre: 'Países', icono: '🌍', palabras: 'FRANCIA ITALIA ALEMANIA PORTUGAL MEXICO BRASIL ARGENTINA CHILE PERU JAPON CHINA INDIA EGIPTO CANADA COLOMBIA URUGUAY CUBA GRECIA SUIZA NORUEGA IRLANDA POLONIA TURQUIA KENIA' },
  deportes: { nombre: 'Deportes', icono: '⚽', palabras: 'FUTBOL TENIS BALONCESTO NATACION CICLISMO ATLETISMO BOXEO GOLF RUGBY VOLEIBOL BALONMANO ESQUI JUDO KARATE PADEL SURF REMO HOCKEY BEISBOL GIMNASIA TRIATLON ESGRIMA' },
  cocina: { nombre: 'Cocina', icono: '🍳', palabras: 'CUCHARA TENEDOR CUCHILLO SARTEN CAZUELA OLLA PLATO VASO TAZA HORNO NEVERA BATIDORA TOSTADORA FREGADERO ESPUMADERA COLADOR MORTERO DELANTAL BANDEJA JARRA FOGON' },
  naturaleza: { nombre: 'Naturaleza', icono: '🌋', palabras: 'MONTE LAGO BOSQUE SELVA DESIERTO VOLCAN CASCADA PLAYA ISLA VALLE COLINA PRADERA ARROYO ACANTILADO CUEVA GLACIAR OASIS PANTANO SIERRA RIO' },
  espacio: { nombre: 'Espacio', icono: '🚀', palabras: 'PLANETA ESTRELLA GALAXIA COMETA METEORITO ASTRONAUTA COHETE SATELITE ORBITA MARTE VENUS JUPITER SATURNO NEPTUNO MERCURIO LUNA ECLIPSE NEBULOSA TELESCOPIO GRAVEDAD' },
};
for (const t of Object.values(TEMAS)) t.palabras = t.palabras.split(' ');
